### ISSUE TITLE
Opera moderation issue

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#10]
![image](https://cloud.githubusercontent.com/assets/3105099/5220231/05d16468-765a-11e4-9a33-8bba8c7d4f60.png)

![image](https://cloud.githubusercontent.com/assets/3105099/5220227/fd3ac290-7659-11e4-9ba4-0d522c860b27.png)

What can we do to fix this?

**Comment by tomasko126** [comment]
@kpeckett For now, just wait until we release next version of CatBlock.

**Comment by itskdog** [comment]
So, here's all the issues we've had:
- Icons of all sizes should be similar in style
  - @tomasko126 can you please sort that out?
- Please remove all unused files and folders e.g. ./tools/tests/
  - @tomasko126 Can you send me a list of files like this so that I can remove them during the build process?

**Comment by tomasko126** [comment]
@kpeckett You can exclude whole /tools folder. I am gonna make changes for problems with icons.

**Comment by itskdog** [comment]
@tomasko126 Can you make a list of every single folder (including /tools) that we don't need so that when I release v1.1.1 we can get this out to the Opera Store quickly with few issues.

**Comment by itskdog** [comment]
All sorted - see the Useless files wiki page
