### ISSUE TITLE
"Don't run on this domain" wizard is broken like crazy

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#104]
It loads at the bottom of the page with broken controls and no URL. Checkboxes on the page also turn into our theme until you close the popup.

**Comment by itskdog** [comment]
=== Filter Lists ===
adblock_custom
  last updated: Thu, 06 Oct 2016 11:13:26 GMT
easylist
  last updated: Thu, 06 Oct 2016 11:13:30 GMT
malware
  last updated: Tue, 27 Sep 2016 06:39:35 GMT

=== Custom Filters ===

@@||www.youtube.com/$document
@@||www.youtube.com/$document
@@||www.wired.com/$document
@@||www.wired.com/$document
@@||www.cpuid.com/$document

=== Settings ===
catblock: true
debug_logging: false
youtube_channel_whitelist: false
whitelist_hulu_ads: false
show_context_menu_items: true
show_advanced_options: false
display_stats: true
display_menu_stats: true
malware-notification: undefined

=== Other Info ===
CatBlock version number: 1.4.9 Developer
UserAgent: Mozilla/5.0 (Windows NT 10.0 Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2873.0 Safari/537.36

**Comment by tomasko126** [comment]
@kpeckett Bug of jQuery UI, we need to update jQuery UI as well.
