### ISSUE TITLE
Office 365 E-mail whitelisted

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#112]
When I go to my student emails, hosted on Office 365 (outlook.office365.com) CatBlock is disabled on the page, and clicking "Enable CatBlock on this page" does nothing. It doesn't even refresh the page.

**Comment by tomasko126** [comment]
@kpeckett CatBlock is disabled on this page by default, 'cause injecting a huge stylesheet has triggered Microsoft's spam filter => every sent e-mail has been flagged as a spam.
