### ISSUE TITLE
Address Firefox review

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#130]
1) We generally don't accept using the 'eval' function. There are many reasons not to use 'eval', and there are alternatives available. You can read more about it here: https://developer.mozilla.org/en/XUL_School/Appendix_C:_Avoid_using_eval_in_Add-ons
- catblock/channels.js line 38, 41

2) Please use non-custom versions of jquery-ui, as well as the stock version of jquery, that match the checksums in https://github.com/mozilla/amo-validator/blob/master/validator/testcases/hashes-allowed.txt

3) Your CSP allows various unsafe operations including remote script execution. Please remove the unsafe-* values and find alternatives for your source code.

**Comment by tomasko126** [comment]
#1 is being addressed in #123, I will take a look at other issues asap.
