### ISSUE TITLE
Firefox Quantum - no menu items show

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#158]
No errors show in popup.html, but background.html outputs the message `_myfilters.blocking is undefined` in `background.js:868`.

As Firefox 57 Codenamed "Quantum" is to launch soon, this is a high-priority bug.

**Comment by tomasko126** [comment]
@kpeckett Are you still able to repro?

**Comment by itskdog** [comment]
not in the release version of Fx 57. Closing as not a bug.

**Comment by aaronliu0130** [comment]
What is this? "bug" "not-a-bug" at the same time?
