### ISSUE TITLE
Content on the site Yandex (https://yandex.ru) is not blocked

### ISSUE THREAD

**Issue by Danilgorshcov** [CatBlock/catblock#167]
Только на английском языке!  
  
Please answer the following questions so that we can process your bug report, otherwise, we may have to ignore it.  
  
**Can you provide detailed steps on how to reproduce the problem?**  
  
![hfchv](https://user-images.githubusercontent.com/46939444/51561232-836fec00-1ea8-11e9-87ba-c6215b89b95a.PNG)

Advertising and services on the home page of Yandex (https://yandex.ru) ceased to be blocked. I just want to keep the search bar and the news. But each time, blocking the rest of the windows, they reappear. Please help me fix it.

Try to block everything except the search bar on (https://yandex.ru), and you will understand what I'm talking about.

**Comment by itskdog** [comment]
Hi there!

Sorry for the late reply.

Have you tried refreshing your filter lists at CatBlock button -> Options -> Filter Lists -> update now?

Let us know if this helps!

**Comment by itskdog** [comment]
This hasn't been touched in 8 months now. I'm closing this.
