### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ghost** [CatBlock/catblock#171]
Please answer the following questions so that we can process your bug report, otherwise, we may have to ignore it.  
  
**Can you provide detailed steps on how to reproduce the problem?**  
  
1.   Why it doesn't replace ads with images
![5222](https://user-images.githubusercontent.com/54793044/82195613-30be0d00-9901-11ea-856f-15e04ab733b7.PNG)

2.   
3.   
  
![533333](https://user-images.githubusercontent.com/54793044/82195637-387db180-9901-11ea-9294-ce663bb0517a.PNG)

**What should happen when you do the above steps**  
  Fix it please
  
**What actually happened?**  
  nothing,i just want you to fix it
  
**Do you have any other comments? If you can, can you please attach a screenshot of the bug?**  
  no
  
--- The questions below are optional but VERY helpful. ---  
  
If unchecking all filter lists fixes the problem, which one filterlist must you check to cause the problem again after another restart?  
  
Technical Chrome users: Go to chrome://extensions ->Developer Mode -> Inspect views: background page -> Console. Paste the contents here:

**Comment by itskdog** [comment]
What you are pointing to is an embedded YouTube video, not what would typically be considered an ad by the ad filter lists. The ads we block or hide are based on the ad filter lists enabled in CatBlock button -> Options -> Filter Lists. Typically these will be EasyList, AdBlock's custom filters, and an additional language-specific list if your browser language set to a language other than English. You would need to contact the filter list for the language of the page directly (or EasyList if it's English - forums.lanik.us) if they have an issue with their filters.

If you wish to hide the ad for yourself, you can click the CatBlock button -> Block an ad on this page, then follow the instructions that appear. Depending on the space CatBlock has, it may or may not show a replacement image in place of the page element you hide.

**Comment by ghost** [comment]
On the site Zamunda.net it doesn't shows pictures it just delete the script
of the ad!Why??

На пн, 18.05.2020 г. в 14:34 Kieran <notifications@github.com> написа:
