### ISSUE TITLE
CatBlock is blocking certain Wikipedia images

### ISSUE THREAD

**Issue by aaronliu0130** [CatBlock/catblock#172]
#### 1. List some steps we can follow to make the bug happen on our end.

1. Go to the "Police Box" Wikipedia page (It might be proxy-specific, as I am using a proxy from en.jinzhao.wiki).
2. Scroll down until you find the image with the subtitles "An 1894 advertisement for the "Glasgow Style Police Signal Box System", sold by the National Telephone Company"

#### 2. When you followed these steps above, what did you think should happen?
![The image should display correctly.](https://user-images.githubusercontent.com/11874211/89727550-8f0a1000-da58-11ea-8851-63ab8fc9f263.png)

#### 3. What actually happened instead?

![The image was blocked.](https://user-images.githubusercontent.com/11874211/89727517-44889380-da58-11ea-8822-4352e23b88eb.png)

#### 4. Finally, click the CatBlock button, then Options, then Support on the page that appears. Provide us with the **debug info** from that page.

```
=== Filter Lists ===
adblock_custom
  last updated: Wed, 05 Aug 2020 07:13:50 GMT
easylist
  last updated: Sun, 09 Aug 2020 06:00:00 GMT
malware
  last updated: Sat, 08 Aug 2020 01:52:25 GMT
chinese
  last updated: Thu, 06 Aug 2020 12:42:29 GMT
warning_removal
  last updated: Sun, 09 Aug 2020 02:52:17 GMT

=== Custom Filters ===
clashofclans.fandom.com##DIV[class="featured-video__wrapper"]
clashofclans.fandom.com##DIV[class="featured-video__wrapper"]
v.qq.com##TXPDIV[class="txp_ad txp_ad_center"]
v.qq.com##TXPDIV[class="txp_ad txp_ad_center"]
@@|https://blockadblock.com/|$document
@@|https://blockadblock.com/|$document
@@|https://blockadblock.com/|$document
@@||blockadblock.com/$document
unicode-table.com##DIV[class="roxotAdContainer"]
unicode-table.com##DIV[class="roxotAdContainer"]
unicode-table.com##DIV[class="roxotAdContainer"]
@@||bilibili.com/$document
@@|https://www.coolmathgames.com/0-clicker-heroes|$document
@@||www.coolmathgames.com/$document

=== Settings ===
catblock: true
debug_logging: false
youtube_channel_whitelist: false
whitelist_hulu_ads: false
show_context_menu_items: true
show_advanced_options: false
display_stats: true
display_menu_stats: true
malware-notification: undefined


=== Other Info ===
CatBlock version number: 1.5.1 Unsupported
UserAgent: Mozilla/5.0 (Windows NT 10.0 Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52
```

#### 5. Any other information you think might be useful for us to know?
No.

**Comment by itskdog** [comment]
Sounds like a problem with one of your ad filter lists. Click the CatBlock button, then "Report an ad on this page" and follow the steps there.

**Comment by aaronliu0130** [comment]
Have you tested the steps?

**Comment by aaronliu0130** [comment]
I just tested things and it seems like the problem's with the easylist.

**Comment by itskdog** [comment]
> Have you tested the steps?

We haven't modified them from the AdBlock code (we're still on AdBlock 2.70 here) so they should still work fine.


> I just tested things and it seems like the problem's with the easylist.

EasyList's forums are at http://foums.lanik.us - you can report that that image is getting blocked there. (You're seeing a cat because it got blocked by EasyList). Feel free to link back to this issue to give them some extra info - just copy and paste in `https://github.com/CatBlock/catblock/issues/172` to your new forum message.

Hope this helps!

**Comment by itskdog** [comment]
(in case it got formatted for you in the e-mail, you want to paste in `https://github.com/CatBlock/catblock/issues/172` - I didn't realise the link would get shortened)
