### ISSUE TITLE
Change name to CatBlock

### ISSUE THREAD

**Issue by tomasko126** [CatBlock/catblock#24]
Right now, we are using AdBlock with CatBlock name,
but after a talk with @kpeckett we decided, that it we should use just CatBlock as an extension name instead.

**Comment by itskdog** [comment]
TODO:
- Info.plist
- manifest.json
- Options page logo
- Button name
- Popup logo
- "Pause AdBlock" string

**Comment by itskdog** [comment]
Going through the i18n files, there's lots of things calling itself "AdBlock" so we need separate strings for each one (yay!)

**Comment by tomasko126** [comment]
Fixed in #54
