### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sanshiro** [CatBlock/catblock#28]
i try to use personalize filters and not working here, working on adblock u_u

**Comment by itskdog** [comment]
Hi!

Where were you looking for these "personalised filters"? Do you mean the "Customise" tab in CatBlock button -> Options?

**Comment by sanshiro** [comment]
yeah, not working here, i use every day adblock to block some entire webpages (##html) but when i try to do that with cat block, not working u_u

**Comment by itskdog** [comment]
Can you use our [support site](http://support.catblock.tk) to communicate? It's easier to keep track there rather than in a GitHub issue. Just click the "New Discussion" button.

**Comment by sanshiro** [comment]
done :)
