### ISSUE TITLE
CatBlock doesn't work with official AdBlock

### ISSUE THREAD

**Issue by tomasko126** [CatBlock/catblock#3]
@kpeckett 

As of today, CatBlock installed via chrome://extensions page doesn't work with official AdBlock installed from Chrome Web Store.

The reason is: AdBlock has defined specific extension id, where sends messages about what selectors will be blocked on the page. When installing CatBlock from chrome://extensions page, CatBlock will get another unique specific ID, not the one we need.

Current work-around: Edit CatBlock's extension ID locally in adblock_start_chrome.js to the one from chrome://extensions

This is the current approach, however I'm not sure about long-time approach. We can either take a look at Chrome Management API, or release CatBlock on CWS and change unique ID in adblock_start_chrome.js OR pack AdBlock with Catblock for Chrome together (like we currently do with Safari version).

What do you think?

**Comment by tomasko126** [comment]
@kpeckett After studying `chrome.management` API, this would need a change in AdBlock itself. However, this change in AdBlock would require another permission, so AdBlock would have to be disabled after code change on AdBlock's side. So this is not a real way we can currently go. We can either decide for releasing CatBlock on CWS and change unique ID in AdBlock or pack AdBlock with CatBlock for Chrome.

**Comment by itskdog** [comment]
As far as I see it, these are our options:
1. Contact the AdBlock team to get them to use our extension ID when we submit our version to the CWS
   - This might take longer, but would make it work for us,but us only
2. Bundle AdBlock with CatBlock, like on Safari.
   - This is quicker, but requires me to get the AdBlock source every time we release.
3. Get the keys from the AdBlock team for the CatBlock web store item, and use that
   - I'm not 100% sure how likely they will do that for us, or if it's possible.

I think that the best way is to work with AdBlock and get them to adjust their code to work with us.

**Comment by tomasko126** [comment]
@kpeckett I'd personally go with second option, since CatBlock for Safari needs up-to-date AdBlock and CatBlock would also work when installed as a dev extension on Chrome/Opera.

**Comment by itskdog** [comment]
Alright. If we can get any l response from the AdBlock team, then we can consider #1 or #3, but for now, let's bundle AdBlock.

**Comment by tomasko126** [comment]
@kpeckett Okay.
