### ISSUE TITLE
Cats inside YouTube videos prevent pressing Cancel on Autoplay

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#35]
On YouTube, cats show up during the autoplay time window, pushing the image down and making the cancel button disappear.

Any way to fix this?

**Comment by tomasko126** [comment]
@kpeckett I haven't been able to reproduce this issue. Can you please take a screenshot and copy it over here? Thanks 👍

**Comment by itskdog** [comment]
Looks like it's been fixed somewhere, either on Google's end or at EasyList.

Closing.
