### ISSUE TITLE
Too many cats on some sites

### ISSUE THREAD

**Issue by itskdog** [CatBlock/catblock#37]
As reported on [Tender](http://support.catblock.tk/discussions/suggestions/2):

> Often an ad will be replaced three pictures that take more space than the original ad did

This is a legitimate concern, as they sometimes take up the entire screen (e.g. on nytimes.com).

Is there a way of adjusting the code to make a limit on the number showing, but still distributing the cats relatively evenly across the page?

**Comment by itskdog** [comment]
This is especially problematic on Yahoo Mail. Look how far I have to scroll down to see the first new message:

![image](https://cloud.githubusercontent.com/assets/3105099/14867048/8962a854-0cbe-11e6-9be0-855e52afa93e.png)

Sometimes it's been further. It has been halfway down the bar before the first message appears.

**Comment by tomasko126** [comment]
Postponing this issue to a later release, since we have to focus on Edge and Firefox releases, which are marked for 1.4 release.

**Comment by itskdog** [comment]
I can confirm this still happens. Whilst YMail doesn't seem to have this anymore, YouTube's autoplay can sometimes get pushed off the bottom of the play window by two cats pushing it down, so you can't always force it to continue and just have to wait instead.

**Comment by tomasko126** [comment]
@kpeckett I will try to find out, why is this happening.

**Comment by tomasko126** [comment]
@kpeckett The more classes (which CatBlock identifies as "they should be hidden by our huge stylesheet") **one** element contains, the more cats are being shown -> leading to showing more cats. PR is on the way..
