### ISSUE TITLE
Flickr search Shows only few images

### ISSUE THREAD

**Issue by studiotbt** [CatBlock/catblock#38]
With Cats from Catblock users and April fools off and only the flickr option on, it only loads 3 images
It appears it has a hard time parsing images a user. Which may be something to do with flickr.
Links tested:
- www.flickr.com/photos/sandiv999/  (3images)
- www.flickr.com/photos/wallacehenning (no images)

Tumblr / Imgur would be great.

**Comment by itskdog** [comment]
@studiotbt @tomasko126

Is this still reproducible?

**Comment by tomasko126** [comment]
@studiotbt @kpeckett It is and here's an explanation, why it happens.
We make a request to the Flickr API with some additional data (which images are usable for CatBlock, specific width and height) and Flickr returns us only those, which we can use in CatBlock.
