### ISSUE TITLE
CatBlock Edge extension popup zoomed in too much

### ISSUE THREAD

**Issue by EphraimB** [CatBlock/catblock#44]

**Comment by itskdog** [comment]
Hi! Can you please let us know which build of Windows you are using?

Thanks

Kieran

**Comment by skylordjason** [comment]
@EphraimB Could be related to DPI depending on your screen resolution.

**Comment by czenzel** [comment]
I also noticed this on a Surface Book (i7, 1TB, dGPU) with Build 14332.rs1_release.160422-1940. DPI is scaled to 200% in Settings (default from Surface Book). I am unable to get a snapshot with the Snipping Tool since the menu pop-up closes.

**Comment by skylordjason** [comment]
@czenzel You can take a delayed snip.

**Comment by czenzel** [comment]
@skylordjason Thanks!

The contents overflow in the container.

![adblockdelayedsnip](https://cloud.githubusercontent.com/assets/3607968/15095688/b631bc58-14a2-11e6-9bc6-20d7a2d2fb61.PNG)

**Comment by itskdog** [comment]
@tomasko126 Any idea what might be causing this?

**Comment by tomasko126** [comment]
@kpeckett @czenzel @skylordjason @EphraimB 
Looks like an Edge bug not on our side.
Unfortunately, we cannot change anything as of now, because the popup cannot be inspected (unlike on Chrome).

**Comment by tomasko126** [comment]
This bug hasn't been resolved in Edge running on 14342 build. I've tried to change a viewport, but without any success. Hopefully this bug will be fixed soon.

**Comment by itskdog** [comment]
Also can anyone here please send feedback to Microsoft through the app in the start menu so that they are aware of the issue?

Thanks
Kieran from CatBlock

**Comment by tomasko126** [comment]
@kpeckett @czenzel @skylordjason @EphraimB 
This issue has been resolved in the latest 14352 build on Fast Ring, therefore I am closing this issue.
