### ISSUE TITLE
Background.js fix: line 1347 - path fix

### ISSUE THREAD

**Issue by NuhaKhaled** [CatBlock/catblock#51]
in js/background.js:
line 1347: chrome.tabs.executeScript(tabId, {file: "ytchannel.js", runAt: "document_start"});

It should be js/ytchannel.js, else it is not working.

**Comment by tomasko126** [comment]
@NuhaKhaled Thanks again for spotting a similar issue. This is a regression of #47, I will fix it in a while.

**Comment by tomasko126** [comment]
@NuhaKhaled This issue has been fixed and I will make another release today :)

**Comment by NuhaKhaled** [comment]
Great, Thank you. Good luck with your Catblock.
